<a href="https://colab.research.google.com/github/prasannashrestha011/Understanding-tensors/blob/main/pytorch.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import torch

In [ ]:
##adding up column to the row,resulting tensor in one D
X = torch.tensor([[1, 2, 3], [4, 5, 6]])
X.sum(axis=1)

tensor([ 6, 15])

In [ ]:
#obtaining mean of tensor
X.sum()/X.numel()

tensor(3.5000)

In [ ]:
#non reduction form of dimension by adding up rows and cols
X.sum(axis=0,keepdim=True)

tensor([[5, 7, 9]])

In [ ]:
A=torch.tensor([[1,2],[3,4]])
A_sum=A.sum(axis=1,keepdim=True)
normalized_A=A/A_sum
normalized_A

tensor([[0.3333, 0.6667],
        [0.4286, 0.5714]])

In [ ]:
A=torch.tensor([[1,2,3],[4,5,6],[7,8,9]])
print("Row cumulative sum= ",A.cumsum(axis=0))
print("Column cumulative sum: \n ",A.cumsum(axis=1))

Row cumulative sum=  tensor([[ 1,  2,  3],
        [ 5,  7,  9],
        [12, 15, 18]])
Column cumulative sum: 
  tensor([[ 1,  3,  6],
        [ 4,  9, 15],
        [ 7, 15, 24]])


In [20]:
X=torch.tensor([1,2,3,4])
Y=torch.tensor([5,6,7,8])
print(torch.dot(X,Y))
print(torch.sum(X*Y))

tensor(70)
tensor(70)


In [71]:
A=torch.tensor([[1,2,3],[4,5,6]],dtype=torch.float32)
x=torch.tensor([1,2,3],dtype=torch.float32)
y=torch.zeros(2,dtype=torch.float32)
y[0]=torch.dot(A[0],x)
y[1]=torch.dot(A[1],x)
y



tensor([14., 32.])

In [79]:
A=torch.ones(2,1)
B=torch.ones(1,2)
A,B,torch.matmul(A,B)

(tensor([[1.],
         [1.]]),
 tensor([[1., 1.]]),
 tensor([[1., 1.],
         [1., 1.]]))